version: "3.9"

services:
  db:
    image: postgres:16
    container_name: studio_pnl1_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studio_pnl
    ports:
      - "5433:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: studio_pnl1_backend
    restart: unless-stopped
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: studio_pnl
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: super_secret_jwt_key_change_me
    ports:
      - "4001:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data1: